default:
  image: ruby:3.4.4

  before_script:
    - apt-get update && apt-get install -y clang
    - gem update --system '3.7.2'
    - gem install bundler -v 2.7.2
    - bundle install

test:
  script:
    - ./bin/test
