default:
  image: ruby:3.4.4

  before_script:
    - apt-get update && apt-get install -y clang
    - gem update --system '3.6.9'
    - gem install bundler -v 2.6.9
    - bundle install

example_job:
  variables:
    RB_SYS_FORCE_INSTALL_RUST_TOOLCHAIN: 'true'
  script:
    - bundle exec rake
