[package]
name = "elelem"
version = "0.1.0"
edition = "2021"
authors = ["mo khan <mo@mokhan.ca>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.7.1" }
